name: release-flow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version - in the form of v1.2.3"
        required: false
        type: string

env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: ${{ secrets.ITCH_GAME }}
  ITCH_USER: ${{ secrets.ITCH_USER }}

permissions:
  contents: write

jobs:
  get-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get game name
        id: get-name
        run: echo "name=$(grep '^name = .*"' Cargo.toml | sed -e 's/name = //' -e 's/"//g')" >> $GITHUB_OUTPUT
    outputs:
      game-name: ${{ steps.get-name.outputs.name }}
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get version
        id: get-version
        run: echo "version=$(grep '^version = .*"' Cargo.toml | sed -e 's/version = //' -e 's/"//g')" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ inputs.version || steps.get-version.outputs.version }}
  get-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changelog
        id: get-changelog
        run: |
          versions=$(grep "^## \[.*]" ChangeLog.md)
          first_two=$(echo "$versions" | head -2)
          start=$(echo "$first_two" | head -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          end=$(echo "$first_two" | tail -1 | sed -e 's/[]\/$*.^[]/\\&/g')
          body=$(sed -n -r "/$start/,/$end/p" ChangeLog.md | head -n -1)
          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      changelog: ${{ steps.get-changelog.outputs.changelog }}
  build-macOS:
    runs-on: macos-latest
    needs: [get-name, get-version, get-changelog]
    env:
      # macOS 11.0 Big Sur is the first version to support universal binaries
      MACOSX_DEPLOYMENT_TARGET: 11.0
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove build script
        run: |
          rm build.rs
      - name: Install rust toolchain for Apple Silicon
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: aarch64-apple-darwin
      - name: Build release for Apple Silicon
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=aarch64-apple-darwin
      - name: Install rust toolchain for Apple x86
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-apple-darwin
      - name: Build release for x86 Apple
        run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path) cargo build --profile dist --target=x86_64-apple-darwin
      - name: Create Universal Binary
        run: |
          lipo -create -output target/dist/${{ env.GAME_NAME }} target/aarch64-apple-darwin/dist/${{ env.GAME_NAME }} target/x86_64-apple-darwin/dist/${{ env.GAME_NAME }}
      - name: Create release
        run: |
          mkdir -p build/macos/src/Game.app/Contents/MacOS/assets
          cp -r assets/ build/macos/src/Game.app/Contents/MacOS/assets
          cp -r credits/ build/macos/src/Game.app/Contents/MacOS/credits
          cp target/dist/${{ env.GAME_NAME }} build/macos/src/Game.app/Contents/MacOS/
          mv build/macos/src/Game.app build/macos/src/${{ env.GAME_NAME }}.app
          ln -s /Applications build/macos/src/
          hdiutil create -fs HFS+ -volname "${{ env.GAME_NAME }}" -srcfolder build/macos/src ${{ env.GAME_NAME }}_${{ env.VERSION }}.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}_macos
          path: ${{ env.GAME_NAME }}_${{ env.VERSION }}.dmg
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_NAME }}_${{ env.VERSION }}.dmg
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_macOS.dmg
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-linux:
    runs-on: ubuntu-latest
    needs: [get-name, get-version, get-changelog]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          chmod +x target/dist/${{ env.GAME_NAME }}
          mv target/dist/${{ env.GAME_NAME }} .
      - name: Bundle release
        run: |
          tar -czf ${{ env.GAME_NAME }}_${{ env.VERSION }}_linux.tar.gz ${{ env.GAME_NAME }} assets credits
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}_linux
          path: ${{ env.GAME_NAME }}_linux.tar.gz
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_NAME }}_${{ env.VERSION }}_linux.tar.gz
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_linux.tar.gz
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-windows:
    runs-on: windows-latest
    needs: [get-name, get-version, get-changelog]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
      BUILD_INSTALLER: ${{ true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install dotnet
        if: ${{ env.BUILD_INSTALLER }}
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: build/windows/installer/global.json
      - name: Build release
        run: |
          cargo build --profile dist
      - name: Prepare release
        run: |
          mkdir target/dist/assets && cp -r assets target/dist/assets
          mkdir target/dist/credits && cp -r credits target/dist/credits
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: target/dist/assets/ target/dist/credits/ target/dist/${{ env.GAME_NAME }}.exe
          dest: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.zip
      - name: Create Installer
        if: ${{ env.BUILD_INSTALLER }}
        run: dotnet build -p:Version=${{ env.VERSION }} -c Release build/windows/installer/Installer.wixproj --output ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows
          path: |
            ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.msi
            ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.zip

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.zip
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.zip
          tag: ${{ env.VERSION }}
          overwrite: true
      - name: Upload installer
        if: ${{ env.BUILD_INSTALLER }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/en-US/${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.msi
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.msi
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-web:
    runs-on: ubuntu-latest
    needs: [get-name, get-version, get-changelog]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: latest
      - name: Add wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build Release
        run: |
          trunk build --release
      - name: Optimize Wasm
        uses: NiklasEi/wasm-opt-action@v2
        with:
          file: dist/*.wasm
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
      - name: Zip release
        uses: vimtor/action-zip@v1.1
        with:
          files: dist/
          dest: ${{ env.GAME_NAME }}_${{ env.VERSION }}_web.zip
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_NAME }}_${{ env.VERSION }}_web.zip
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_web.zip
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-for-iOS:
    runs-on: macos-latest
    timeout-minutes: 30
    needs: [get-name, get-version, get-changelog]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios
      - name: Build app for iOS
        run: |
          cd mobile
          make xcodebuild-iphone-release
          mkdir Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload
          zip -r ${{ env.GAME_NAME }}.zip Payload
          mv ${{ env.GAME_NAME }}.zip ${{ env.GAME_NAME }}${{ env.VERSION }}_ios.ipa
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mobile/${{ env.GAME_NAME }}_${{ env.VERSION }}_ios.ipa
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_unsigned_ios.ipa
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-for-Android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [get-name, get-version, get-changelog]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
      CHANGELOG: ${{ needs.get-changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Add Android targets
        # could add more targets like armv7-linux-androideabi here (then also add to cargo-apk config)
        run: rustup target add aarch64-linux-android
      - name: Install Cargo APK
        run: cargo install --force cargo-apk
      - name: Build app for Android
        # This uses a debug build, since release builds require keystore configuration
        # For AAB builds that can be pushed to the Play store, see the release-android-google-play workflow.
        run: |
          ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --package mobile
          ls -la target/debug/apk
          mv target/debug/apk/${{ env.GAME_NAME }}.apk ${{ env.GAME_NAME }}_${{ env.VERSION }}_android.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}_android
          path: ${{ env.GAME_NAME }}_${{ env.VERSION }}_android.apk
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GAME_NAME }}_${{ env.VERSION }}_android.apk
          asset_name: ${{ env.GAME_NAME }}_${{ env.VERSION }}_android.apk
          release_name: ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          tag: ${{ env.VERSION }}
          overwrite: true
  deploy-itch:
    runs-on: ubuntu-latest
    needs:
      [
        get-name,
        get-version,
        build-linux,
        build-macOS,
        build-windows,
        build-for-Android,
        build-for-iOS,
      ]
    env:
      GAME_NAME: ${{ needs.get-name.outputs.game-name }}
      VERSION: ${{ needs.get-version.outputs.version }}
    strategy:
      matrix:
        platform:
          [
            { suffix: _linux.tar.gz, channel: linux },
            { suffix: _macOS.dmg, channel: osx },
            { suffix: _windows.msi, channel: windows },
            { suffix: _android.apk, channel: android },
            { suffix: _ios.ipa, channel: ios },
          ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GAME_NAME }}_${{ env.VERSION }}${{ matrix.platform.suffix }}
      - name: Deploy to Itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: ${{ matrix.platform.channel }}
          PACKAGE: ${{ env.GAME_NAME }}_${{ env.VERSION }}_windows.msi
